name = "frameshot-images"
main = "src/index.js"
compatibility_date = "2024-04-17"
compatibility_flags = ["nodejs_compat"]

# R2 bucket binding
[[r2_buckets]]
binding = "THUMBNAILS"
bucket_name = "frameshot-thumbnails"

[env.production]
workers_dev = false